(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["RationalArithmeticCoding`"]

RationalACEncoder::usage="RationalACEncoder[S,p,c1] encodes a sequence of symbols S. Functions p[s,S] and c1[s,S] are conditional probability mass functions of the symbol s given preceding sequence S."

RationalACDecoder::usage=
"RationalACEncoder[v,\[Psi],stop,p,c1] decodes an interval v into a sequence of symbols. Function \[Psi][v,S] gives the next symbol given current rescaled interval and preceding symbols sequence S. Function stop[S,v] decides whether a sequence S with rescaled interval v should be terminated. Functions p[s,S] and c1[s,S] are conditional probability mass functions of the symbol s given preceding sequence S."

Begin["`Private`"]

RationalACEncoder[sequence_,p_,c1_]:=Module[
{\[CapitalPhi]},
\[CapitalPhi][{}]=({
 {0},
 {1}
});
\[CapitalPhi][S_]:=\[CapitalPhi][S]=({
 {1, c1[Last[S],Most[S]]},
 {0, p[Last[S],Most[S]]}
}).\[CapitalPhi][Most[S]];
\[CapitalPhi][sequence]
]
RationalACDecoder[interval_,\[Psi]_,stop_,p_,c1_]:=Module[
{\[CapitalPsi],rescale},
rescale[v_,s_,S_]:=(v-c1[s,S])/p[s,S];
\[CapitalPsi][v_]:=\[CapitalPsi][{\[Psi][v,{}]},rescale[v,\[Psi][v,{}],{}]];
\[CapitalPsi][S_,v_]:=\[CapitalPsi][S,v]=If[
stop[Last[S],v],
S,
\[CapitalPsi][Append[S,\[Psi][v,S]],rescale[v,\[Psi][v,S],S]]
];
\[CapitalPsi][interval]
]

End[]

EndPackage[]
